spring:
  application:
    name: application-command
  datasource:
    url: jdbc:mysql://mysql-database:3306/company
    #url: jdbc:mysql://localhost:3306/company
    username: application-command
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: rabbitmq
    #host: localhost
    port: 5672
    username: user
    password: 1234
    virtual-host: /

server:
  port: 8080

communications:
  api-authorize-url: "https://util.devi.tools"
  api-notification-url: "https://util.devi.tools"

messaging:
  exchanges:
    dlx: "company.dlx"
    direct: "company.direct"
  queues:
    transaction-received: "company.notification.transaction.received"
    transaction-received-dlq: "company.notification.transaction.received.dlq"
  routing-key:
    transaction-received: "transaction.received"
